### ISSUE TITLE
OC 8.1 news checker kills session

### ISSUE THREAD

**Issue by LennartRoeder** [owncloud-archive/news-chrome-notifier#3]
With OC 8.1 the news checker kills the OC session after about one minute. It does not happen with an empty feed. It might be a problem with certain feeds or just with a specific. I this is still maintained and you need further info, pls tell me.

The details are here: https://github.com/owncloud/core/issues/17488

**Comment by gilfrade** [comment]
I am getting the same anomally, any news about this issue?

**Comment by Popyllol** [comment]
I have the same issue. When I enable he news plugin I get a session dropdown after a few seconds.
In the log I can see:

```
{"reqId":"I7mgR9MLp5p0jKvloBzh","remoteAddr":"<ip>","app":"index","message":"Exception: {\"Exception\":\"OC\\\\AppFramework\\\\Middleware\\\\Security\\\\SecurityException\",\"Message\":\"CORS requires basic auth\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud-8.1\\\/lib\\\/private\\\/appframework\\\/middleware\\\/middlewaredispatcher.php(92): OC\\\\AppFramework\\\\Middleware\\\\Security\\\\CORSMiddleware->beforeController(Object(OCA\\\\News\\\\Controller\\\\FeedApiController), 'index')\\n#1 \\\/var\\\/www\\\/owncloud-8.1\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(88): OC\\\\AppFramework\\\\Middleware\\\\MiddlewareDispatcher->beforeController(Object(OCA\\\\News\\\\Controller\\\\FeedApiController), 'index')\\n#2 \\\/var\\\/www\\\/owncloud-8.1\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\News\\\\Controller\\\\FeedApiController), 'index')\\n#3 \\\/var\\\/www\\\/owncloud-8.1\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('FeedApiControll...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#4 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#5 \\\/var\\\/www\\\/owncloud-8.1\\\/lib\\\/private\\\/route\\\/router.php(274): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#6 \\\/var\\\/www\\\/owncloud-8.1\\\/lib\\\/base.php(873): OC\\\\Route\\\\Router->match('\\\/apps\\\/news\\\/api\\\/...')\\n#7 \\\/var\\\/www\\\/owncloud-8.1\\\/index.php(40): OC::handleRequest()\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud-8.1\\\/lib\\\/private\\\/appframework\\\/middleware\\\/security\\\/corsmiddleware.php\",\"Line\":86}","level":4,"time":"August 17, 2015 19:47:41"}
```

The news verifyer says that all tests return OK:

```
# su -s /bin/bash - www-data -c "/usr/bin/php -f /var/www/owncloud/occ news:verify-install"
 558/558 [============================] 100%

Installation verified, everything OK!
```

```
# dpkg -l | grep owncloud
ii  owncloud                              8.1.1-1                                 all          The ownCloud Server - Private file sync and share server
ii  owncloud-3rdparty                     8.1.1-1                                 all          The ownCloud app owncloud-3rdparty
ii  owncloud-app-activity                 8.1.1-1                                 all          The ownCloud app owncloud-app-activity
ii  owncloud-app-encryption               8.1.1-1                                 all          The owncloud subpackage owncloud-app-encryption
ii  owncloud-app-external                 8.1.1-1                                 all          The ownCloud app owncloud-app-external
ii  owncloud-app-files                    8.1.1-1                                 all          The ownCloud app owncloud-app-files
ii  owncloud-app-files-external           8.1.1-1                                 all          The ownCloud app owncloud-app-files-external
ii  owncloud-app-files-locking            8.1.1-1                                 all          The ownCloud app owncloud-app-files-locking
ii  owncloud-app-files-pdfviewer          8.1.1-1                                 all          The ownCloud app owncloud-app-files-pdfviewer
ii  owncloud-app-files-sharing            8.1.1-1                                 all          The ownCloud app owncloud-app-files-sharing
ii  owncloud-app-files-texteditor         8.1.1-1                                 all          The ownCloud app owncloud-app-files-texteditor
ii  owncloud-app-files-trashbin           8.1.1-1                                 all          The ownCloud app owncloud-app-files-trashbin
ii  owncloud-app-files-versions           8.1.1-1                                 all          The ownCloud app owncloud-app-files-versions
ii  owncloud-app-files-videoviewer        8.1.1-1                                 all          The ownCloud app owncloud-app-files-videoviewer
ii  owncloud-app-firstrunwizard           8.1.1-1                                 all          The ownCloud app owncloud-app-firstrunwizard
ii  owncloud-app-gallery                  8.1.1-1                                 all          The ownCloud app owncloud-app-gallery
ii  owncloud-app-provisioning-api         8.1.1-1                                 all          The ownCloud app owncloud-app-provisioning-api
ii  owncloud-app-templateeditor           8.1.1-1                                 all          The ownCloud app owncloud-app-templateeditor
ii  owncloud-app-user-external            8.1.1-1                                 all          The ownCloud app owncloud-app-user-external
ii  owncloud-app-user-ldap                8.1.1-1                                 all          The ownCloud app owncloud-app-user-ldap
ii  owncloud-app-user-webdavauth          8.1.1-1                                 all          The ownCloud app owncloud-app-user-webdavauth
ii  owncloud-config-apache                8.1.1-1                                 all          The ownCloud configuration for the apache web server
ii  owncloud-server                       8.1.1-1                                 all          The owncloud-server package
```

```
# su -s /bin/bash - www-data -c "/usr/bin/php -f /var/www/owncloud/occ app:list"
Enabled:
 - activity: 2.0.1
 - bookmarks: 0.4
 - calendar: 0.7.1
 - calendarplus: 1.0.1
 - contacts: 0.4.0.0
 - documents: 0.9.0
 - external: 1.2
 - files: 1.1.10
 - files_antivirus: 0.6.1
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_reader: 0.6.0
 - files_share_qr: 0.1
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - galleryplus: 2.0.5
 - music: 0.3.5
 - news: 6.0.1
 - notes: 1.0.0
 - roundcube: 2.6.1
 - search_lucene: 0.6.0
 - tasks: 0.5.1
 - tasksplus: 1.0.0
 - templateeditor: 0.1
 - user_external: 0.4
```

I love the news app... a fix would make my day!

Greetings,
   Lars

**Comment by jancborchardt** [comment]
cc @alepolidori @BernhardPosselt maybe you can fix this.

**Comment by BernhardPosselt** [comment]
Issue here at hand is that the checker plugin seems to use the session which is wrong. It needs to send proper basic auth headers ;)
